### ISSUE TITLE
Tweets with truncated links break the plugin

### ISSUE THREAD

**Issue by elephantium** [ezraverheijen/timeline-twitter-feed#2] opened 2015-03-03 16:46 UTC
This shows up in a couple of different ways.

First, the following tweet breaks the plugin when "Link to #hashtags" is set:

`RT @vivlibrary: New books have been added to our @MackinVIA account!  It won&#039;t be closed over spring break!  #vivnation #eBooks #Lonestarli…`

Second, the following tweet breaks the plugin regardless of settings:

`RT @shannonmmiller: #sasksla I wanted to share how to add resources, links, videos and student created content to @MackinVIA <a href="http://t.co/Sn</p>`

I've tracked this down to the regex in class-timeline-twitter-feed-shortcode.php, lined 158-170, but I'm not sure that I can fix the regex (relevant:  http://stackoverflow.com/questions/1732348/regex-match-open-tags-except-xhtml-self-contained-tags)

**Comment by ezraverheijen** [comment] 2015-03-03 22:32
Thanks for reporting!

Do you still have the beta version 0.9 installed?
The problem with the `&#039;` was fixed in version 1.0, see https://wordpress.org/support/topic/encoding-7

The second bug is something I can't reproduce with the latest version of the plugin. If I pass the plugin the exact string you give, or if I pull the exact tweet from the Twitter API nothing breaks.
If I use version 0.9 the tweet breaks indeed (due to the old regex). Instead of `RT @shannonmmiller: #sasksla I wanted...` it turns into `RT @shannonmmiller: / I wanted...`. The hashtag breaks.

Please update the plugin to the latest version. This should solve your issues with the plugin.

**Closed by ezraverheijen** 2015-03-03 22:32 UTC

**Comment by elephantium** [comment] 2015-03-04 16:33
Thanks for replying so quickly!

I definitely am using the latest version of the plugin (1.1 according to readme.txt).  I should have mentioned that I'm running this on a Windows server; I now suspect that is part of the issue.  With the tweets I mentioned, even when they're in the middle of the group of tweets being parsed, all output from the plugin stops after the offending tweet -- so only 3 tweets show up when I'm expecting 5, and the summary text/link "(about 15 hours ago)" isn't there for the "breaking" tweet.

Oh, I should also clarify that the closing paragraph tag isn't actually part of the tweet -- that's what shows up when things break.

I tried running `substr($text, -2);` to get the last characters in the tweet; this kills all further output from the plugin (if I put it before the first `preg_replace` call, that tweet doesn't appear in the output).  Changing that to `mb_substr` prevents the break.

From there, I tried changing the `preg_replace` calls to `mb_ereg_replace`; that fixes things on my system.
